[package]
name = "mokita-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = "0.8.4"
clap = { version = "4.5.41", features = ["derive"] }
config = "0.15.13"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "tls-native-tls", "postgres", "derive", "chrono", "migrate", "uuid", "macros"] }
thiserror = "2.0.17"
tokio = { version = "1.46.1", features = ["full"] }
tokio-cron-scheduler = "0.15.1"
tracing = "0.1.44"
tracing-appender = "0.2.4"
tracing-subscriber = { version = "0.3.22", features = ["json"] }
